In [ ]:
import tensorflow as tf
import numpy as np
import IPython.display as display
import tensorflow as tf

In [ ]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
x=tf.matmul([[1]],[[2,3]])
print(x)

print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [ ]:
ndarray=np.ones([3,3])
print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [ ]:
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
y=tf.random.uniform([3,3])

print("Is there a GPU available: "),
print(tf.config.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
[]
Is the Tensor on GPU #0:  
False


In [ ]:
import time 

def time_matmul(x):
  start=time.time()
  for loop in range(10):
    tf.matmul(x,x)

    result=time.time()-startprint('10 loops:{:0.2f}ms'.format(1000*result))

In [ ]:
ds_tensors = tf.data.Dataset.from_tensor_slices(['my name is livin'])

In [ ]:
list(ds_tensors)

[<tf.Tensor: shape=(), dtype=string, numpy=b'my name is livin'>]

In [ ]:
layers=tf.keras.layers.Dense(100)
layers=tf.keras.layers.Dense(10,input_shape=(None,5))

In [ ]:
layers(tf.zeros([10,5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
layers.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.33577004,  0.513552  ,  0.5584006 , -0.36024508, -0.5758161 ,
          0.53735644,  0.44071537,  0.2379564 , -0.00094151,  0.303941  ],
        [ 0.21058428, -0.47124338,  0.1599229 , -0.07722831,  0.4752856 ,
          0.5470069 , -0.4755436 ,  0.49176484,  0.6304589 , -0.39988768],
        [-0.5441721 ,  0.26921445, -0.17184746, -0.04810959,  0.38372034,
         -0.2356385 ,  0.30018395, -0.10730863,  0.2907527 ,  0.09047246],
        [-0.22384167, -0.28119734,  0.49701542, -0.33717737,  0.38211316,
          0.34884465, -0.33187637, -0.5540817 ,  0.30148256, -0.16543093],
        [ 0.3945033 , -0.30714363,  0.2578146 ,  0.5197483 ,  0.06730849,
          0.50522894,  0.60893255, -0.12133747, -0.10644782, -0.37167504]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [ ]:
layers.kernel,layers.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.33577004,  0.513552  ,  0.5584006 , -0.36024508, -0.5758161 ,
          0.53735644,  0.44071537,  0.2379564 , -0.00094151,  0.303941  ],
        [ 0.21058428, -0.47124338,  0.1599229 , -0.07722831,  0.4752856 ,
          0.5470069 , -0.4755436 ,  0.49176484,  0.6304589 , -0.39988768],
        [-0.5441721 ,  0.26921445, -0.17184746, -0.04810959,  0.38372034,
         -0.2356385 ,  0.30018395, -0.10730863,  0.2907527 ,  0.09047246],
        [-0.22384167, -0.28119734,  0.49701542, -0.33717737,  0.38211316,
          0.34884465, -0.33187637, -0.5540817 ,  0.30148256, -0.16543093],
        [ 0.3945033 , -0.30714363,  0.2578146 ,  0.5197483 ,  0.06730849,
          0.50522894,  0.60893255, -0.12133747, -0.10644782, -0.37167504]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [ ]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self,num_outputs):
    super(MyDenseLayer,self).__init__()
    self.num_outputs=num_outputs

  def build(self,input_shape):
    self.kernel=self.add_weight('kernel',
                                shape=[int(input_shape[-1]),
                                       self.num_outputs])
  def call(self,inputs):
      return tf.matmul(inputs,self.kernel)
layer=MyDenseLayer(10)

In [ ]:
_=layers(tf.zeros([10,5]))

In [ ]:
print([var.name for var in layer.trainable_variables])

[]
