In [ ]:
import tensorflow as tf

In [ ]:
tf.compat.v1.disable_eager_execution()
w=tf.Variable(.3,tf.float32)
b=tf.Variable(-.3,tf.float32)
x=tf.compat.v1.placeholder(tf.float32)
model=w*x+b
init=tf.compat.v1.global_variables_initializer()
sess=tf.compat.v1.Session()
sess.run(init)
print(sess.run(model,{x:[1,2,3,4]}))

[0.         0.3        0.6        0.90000004]


In [ ]:
tf.compat.v1.disable_eager_execution()
y=tf.compat.v1.placeholder(tf.float32)
squared=tf.square(model-y)
loss=tf.reduce_sum

In [ ]:
y

<tf.Tensor 'Placeholder_1:0' shape=<unknown> dtype=float32>

In [ ]:
import torch

In [ ]:
print("python list operation")
a=[1,2,3]
b=[4,5,6]
print(a+b)
try:
  print(a*b)
except TypeError:
  print("a*b is not working in the list")

python list operation
[1, 2, 3, 4, 5, 6]
a*b is not working in the list


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
try:
  print(a*b)
except TypeError:
  print("a*b is not working in the list")

[5 7 9]
[ 4 10 18]


good great performance


In [ ]:
print("Python list operations:")
a = [1,2,3]
b = [4,5,6]
print("a+b:", a+b)
try:
    print(a*b)
except TypeError:
    print("a*b has no meaning for Python lists")
print()
print("numpy array operations:")
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a+b:", a+b)
print("a*b:", a*b)

Python list operations:
a+b: [1, 2, 3, 4, 5, 6]
a*b has no meaning for Python lists

numpy array operations:
a+b: [5 7 9]
a*b: [ 4 10 18]


In [ ]:
a=np.array([[1,2,5],
            [3,4,6]])
b=np.array([7,8,9])

print("a+b\n",a+b)


a+b
 [[ 8 10 14]
 [10 12 15]]


In [ ]:
def square(x):

  return np.power(x, 3)
def leaky_relu(x):

  return np.maximum(0.2 * x, x)

In [ ]:
square(a)

array([[  1,   8, 125],
       [ 27,  64, 216]])

In [ ]:
def tend(m):
  return np.power(m,7)

In [ ]:
k=np.array([[1,2,3],
            [4,5,6]])

In [ ]:

tend(k)

array([[     1,    128,   2187],
       [ 16384,  78125, 279936]])

In [ ]:
square(k)

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [ ]:
maja=np.array([[0,-1,-4],
               [6,-10,8]])
leaky_relu(maja)

array([[ 0. , -0.2, -0.8],
       [ 6. , -2. ,  8. ]])

In [ ]:
def relu(data):
  return data.clip(min=0)

In [ ]:
relu(maja)

array([[0, 0, 0],
       [6, 0, 8]])

In [ ]:
maja.T.shape

(3, 2)

In [ ]:
maja

array([[  0,  -1,  -4],
       [  6, -10,   8]])

In [ ]:
print(np.square(0.001))

1e-06


In [ ]:
neram=np.array([[[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]],
               [[13,14,15,16],
                [17,18,19,20],
                [21,22,23,24]]])

In [ ]:
neram.shape

(2, 3, 4)

In [ ]:
n1=np.random.randint(0,50,size=(2,3,4))

In [ ]:
n2=np.random.randint(50,100,size=(2,3,4))

In [ ]:
from typing import Callable
from typing import List

In [ ]:
input

<bound method Kernel.raw_input of <google.colab._kernel.Kernel object at 0x7f46be585410>>

In [ ]:
input

<bound method Kernel.raw_input of <google.colab._kernel.Kernel object at 0x7f46be585410>>